version: '3'
services:
  content-server:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./images:/usr/share/nginx/html/images
    ports:
      - "80:80"

  proxy-server:
    image: nginx-purge-module:latest
    volumes:
      - ./nginx-purge.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
