version: '3.1'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--innodb_flush_log_at_trx_commit=2']
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
